import { Metadata } from 'next';
import { Container } from '@/shared/components';
import { Header } from '@/widgets';

export const metadata: Metadata = {
    title: 'Next Pizza | Корзина',
    description: 'Generated by Next.js',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className='min-h-screen bg-[#f4f1ee]'>
            <Container>
                <Header className='border-gray-200' hasSearch={false} hasCart={false} />
                {children}
            </Container>
        </main>
    );
}
